FROM amazoncorretto:11
LABEL maintainer="gexterio@gmail.com"
WORKDIR /app
COPY target/university-0.0.1-SNAPSHOT.jar university.jar
ENTRYPOINT java -jar university.jar
EXPOSE 8080
VOLUME /university/data