server:
  port: 8080
spring:
  application:
    name: "university-service"
  datasource:
    url: "jdbc:postgresql://localhost:5433/postgres"
    username: "postgres"
    password: "pass"
  flyway:
    baseline-on-migrate: false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: "UTC"




